name: mivaai
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aom=3.6.0=hcec6c5f_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - beautifulsoup4=4.13.4=py313hecd8cb5_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py313ha0efc16_0
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.16.0=h08824b9_6
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py313h1962661_0
  - cpython=3.13.9=py313hd8ed1ab_101
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h6c40b1e_0
  - debugpy=1.8.17=py313hff8d55d_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=py313hecd8cb5_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.55.3=py313h46256e1_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - gettext=0.21.0=h4e8c18a_2
  - graphite2=1.3.14=he9d5cce_1
  - h11=0.16.0=py313hecd8cb5_0
  - harfbuzz=10.2.0=h060d35a_1
  - httpcore=1.0.9=py313hecd8cb5_0
  - httpx=0.28.1=py313hecd8cb5_0
  - icu=73.1=hcec6c5f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.5=py313hecd8cb5_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jiter=0.6.1=py313hcc58cb1_0
  - joblib=1.5.1=py313hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_widgets=3.0.15=py313hecd8cb5_0
  - kiwisolver=1.4.8=py313h6d0c2b6_0
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libavif=1.1.1=h46256e1_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libmpdec=4.0.0=h46256e1_0
  - libopenblas=0.3.29=h3f8574a_0
  - libpng=1.6.39=h6c40b1e_0
  - libsodium=1.0.20=hfdf4475_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - matplotlib=3.10.0=py313hecd8cb5_1
  - matplotlib-base=3.10.0=py313hae83f4b_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.11.0=py313hc046980_0
  - numpy=2.3.1=py313h1a2ec72_0
  - numpy-base=2.3.1=py313hce0bb57_0
  - openai=1.77.0=py313hecd8cb5_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.5.4=h230baf5_0
  - packaging=25.0=py313hecd8cb5_0
  - pandas=2.3.1=py313h19bd442_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=h9b97e30_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py313h25d8182_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=hb254d66_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py313hcb05632_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pydantic-core=2.33.2=py313hb0c8e1d_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py313hecd8cb5_0
  - python=3.13.5=h81a7116_100_cp313
  - python-dateutil=2.9.0post0=py313hecd8cb5_2
  - python-dotenv=1.1.0=py313hecd8cb5_0
  - python-gil=3.13.9=h4df99d1_101
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - pytz=2025.2=py313hecd8cb5_0
  - pyzmq=27.1.0=py312hb7d603e_0
  - readline=8.3=h49f2429_0
  - scikit-learn=1.7.1=py313h1756fbf_0
  - scipy=1.16.0=py313hcd1e4c7_0
  - setuptools=72.1.0=py313hecd8cb5_0
  - six=1.17.0=py313hecd8cb5_0
  - soupsieve=2.5=py313hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=py313h653c010_0
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.1=py313h46256e1_0
  - tqdm=4.67.1=py313h653c010_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=py313hecd8cb5_0
  - typing_extensions=4.12.2=py313hecd8cb5_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py313hecd8cb5_0
  - widgetsnbextension=4.0.13=py313hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - aiofiles==24.1.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - audioop-lts==0.2.2
      - brotli==1.1.0
      - certifi==2025.10.5
      - click==8.3.0
      - fastapi==0.121.0
      - ffmpy==0.6.4
      - filelock==3.20.0
      - fsspec==2025.10.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - hf-xet==1.2.0
      - huggingface-hub==1.0.1
      - idna==3.11
      - jinja2==3.1.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - orjson==3.11.4
      - pydantic==2.11.10
      - pydub==0.25.1
      - pypdf2==3.0.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - rich==14.2.0
      - ruff==0.14.3
      - safehttpx==0.1.7
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.49.3
      - tomlkit==0.13.3
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
      - websockets==15.0.1
prefix: /opt/miniconda3/envs/mivaai
